name: Sync upstream

on:
  schedule:
    - cron: "0 3 * * *"   # 每天 UTC 3点运行
  workflow_dispatch:       # 允许手动运行

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Sync upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote add upstream https://github.com/fscarmen/sing-box.git || true

          git fetch upstream

          git checkout main
          git reset --hard upstream/main
          git push --force origin main

          git checkout custom
          git rebase upstream/main
          git push --force-with-lease origin custom
